### ISSUE TITLE
Unable to compile with Xcode12.5 beta3 

### ISSUE THREAD

**Issue by JaapWijnen** [GottaGetSwifty/CodableWrappers#13]
Can't compile on macOS 11 (11.3 beta 20E5229a) using XCode 12.5 beta 3 (12E5244e) due to following error:
`'Float16' is unavailable in macOS`
Not sure what the extent of this is or if it does build for other macOS versions? If not we can simply rewrite the swift version check as:
`#if swift(>=5.4) && !os(macOS)`

**Comment by GottaGetSwifty** [comment]
v2.0.2 works for me on macOS 11.2.3 with Xcode 12.4.

`Flaot16` _should_ be available in macOS 11 [according to the documentation](https://developer.apple.com/documentation/swift/float16), but it's possible they introduced a bug in a beta. I'll check when it's released, but until then I'd recommend forking it and trying to get it to build 🙂

**Comment by JaapWijnen** [comment]
Thanks :) Yeah that's exactly what I did for now. Just thought I'd let you know but indeed if it builds for 12.4 on macOS then let's just hope 12.5 releases soon :) Thanks!

**Comment by Brett-Best** [comment]
The Xcode 12.5RC doesn’t work with the Float16 for macCatalyst. My PR #11 might need to be applied again. I’ve raised a feedback with Apple. See repo: https://github.com/Brett-Best/Float16Catalyst
<img width="887" alt="Screen Shot 2021-04-22 at 11 09 35 pm" src="https://user-images.githubusercontent.com/6104381/115719819-cf7ba500-a3bf-11eb-92a9-e8aea83da5df.png">

**Comment by GottaGetSwifty** [comment]
@Brett-Best @JaapWijnen 
I think the new release should fix it in a way that doesn't affect Linux:
https://github.com/GottaGetSwifty/CodableWrappers/releases/tag/2.0.3 

Please let me know when you have time to test!

**Comment by Brett-Best** [comment]
@GottaGetSwifty doesn’t work with the Any Mac (Mac Catalyst) target unfortunately

**Comment by JaapWijnen** [comment]
@GottaGetSwifty I was able to replace my fork! So works for me on mac.

**Comment by GottaGetSwifty** [comment]
@Brett-Best Doesn't work as in doesn't compile, or Float16 isn't available?

**Comment by Brett-Best** [comment]
@GottaGetSwifty doesn’t compile with the error `'Float16' is unavailable in Mac Catalyst`, it should work with Apple Silicon Catalyst but not Intel Catalyst

**Comment by GottaGetSwifty** [comment]
@Brett-Best I think I found the right combination, `#if`s seem a bit finicky. Please try https://github.com/GottaGetSwifty/CodableWrappers/releases/tag/2.0.4

**Comment by Brett-Best** [comment]
@GottaGetSwifty that works thanks, also I think it is possible for some linux platforms to have the Float16 type -- going on the Swift source code it looks they do a fairly complicated series of checks before marking it as available. Something we wouldn’t be able to achieve with the current set of #if available to us

**Comment by GottaGetSwifty** [comment]
@Brett-Best Good to know. If it pops up again should probably just have a separate branch with out it.

**Comment by GottaGetSwifty** [comment]
@Brett-Best Also thanks again!!
