### ISSUE TITLE
Update CodableWrappers in CocoaPods library

### ISSUE THREAD

**Issue by K-Be** [GottaGetSwifty/CodableWrappers#18]
Last version of CodableWrappers in Cococapods is 2.0.0. 
Can you update version in CococaPods?

**Comment by aserdobintsev** [comment]
@GottaGetSwifty as I mentioned in #17, to register version update in CocoaPods 
you shoud do `pod trunk push CodableWrappers.podspec`

**Comment by tomasandrle** [comment]
@GottaGetSwifty this would help me immensely.

**Comment by GottaGetSwifty** [comment]
Apologies for the delay here, thought it was done but had to create a new session.
