### ISSUE TITLE
Decoding empty JSON string value into nil with Codable

### ISSUE THREAD

**Issue by WingCH** [GottaGetSwifty/CodableWrappers#19]
normal case:
```json
{
    "maintenance": true
}

{
    "maintenance": false
}
```

If there is no maintenance station then it will become `empty  string`
```json
{
    "maintenance": ""
}
```

i want to have `nil` if maintenance is empty string in json
```swift
struct Demo: Codable {
    var maintenance: Bool?
}
```

Is there a good way to do it?

**Comment by GottaGetSwifty** [comment]
I think something like this should work, no testing done though: 
```
struct NilBoolFallback: FallbackValueProvider {
    public static var defaultValue: Bool? { nil }
}

@FallbackDecoding<NilBoolFallback>
var maintenance: Bool?
```

The idea being if it's anything _other_ than a Bool (and thus fails to decode) it will use the defaultValue

**Comment by GottaGetSwifty** [comment]
@WingCH Re-open if you have any more questions
