### ISSUE TITLE
Make all wrappers optional by default

### ISSUE THREAD

**Issue by Igralino** [GottaGetSwifty/CodableWrappers#20]
I've used CodableWrappers for a while and very liked it. 

But it was inconvenient to write _OptionalCoding_ every time I use wrapper on optional variable. Isn't it possible to make all wrappers Optional by default?

**Comment by GottaGetSwifty** [comment]
The issue I came across is you can wrap a non-optional value in Optional, but not vice-versa. And there are encoding/decoding differences with Optional values, so they need to be differentiated somehow.

If you come up with a way to make it work the other way around please let me know!
