### ISSUE TITLE
Push new version to CocoaPods

### ISSUE THREAD

**Issue by balint-lorand** [GottaGetSwifty/CodableWrappers#21]
When I install CodableWrappers via cocoapods, I only get version 2.0.0 instead of the latest 2.0.6. I need this newer version, and as I searched around I found others have the same issue and suggested:
"to update register version update in CocoaPods you shoud do `pod trunk push CodableWrappers.podspec`"
Please do so, so we can use this awesome library. Thank you!

**Comment by GottaGetSwifty** [comment]
Sorry for the delay, thought it pushed but it needed a new session.
