### ISSUE TITLE
Is it possible to decode to custom types?

### ISSUE THREAD

**Issue by staticdreams** [GottaGetSwifty/CodableWrappers#22]
Hi,

I'm looking for a way to map/decode json values to custom Enums.

For instance my API return `status` value which may be something like -1, 0 or 1
I also have an enum:

    enum Status: Int {
        case deleted = -1
        case inactive = 0
        case active = 1
    }

Can I map these together? I tried implementing a custom mapper from your example buy it doest seem to accept custom types, such as `Status `. I want to be able to do something like this: 

` return Status(rawValue: -1)` 

and get my custom type

**Comment by DrowsySquirrel** [comment]
How about making your `Status` conform to `Codable`?
```
enum Status: Int, Codable {
    case deleted = -1
    case inactive = 0
    case active = 1
}
```

**Comment by GottaGetSwifty** [comment]
@staticdreams As @earthworkerman mentioned, this should work if you adopt Codable. Please re-open if you have issues
