### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nkavian** [GottaGetSwifty/CodableWrappers#31]
https://github.com/GottaGetSwifty/CodableWrappers/blob/master/Sources/CodableWrappers/Core/OptionalWrappers.swift#L76

I think this
`public struct OptionalEncoding<CustomDecoderWrapper: StaticEncoderWrapper>: OptionalEncodable {`
should be
`public struct OptionalEncoding<CustomEncoderWrapper: StaticEncoderWrapper>: OptionalEncodable {`

**Comment by GottaGetSwifty** [comment]
Fixed on main
