### ISSUE TITLE
`DateFormatterStaticDecoder` throws `valueNotFound` error instead of `dataCorrupted` error

### ISSUE THREAD

**Issue by Brett-Best** [GottaGetSwifty/CodableWrappers#33]
https://github.com/GottaGetSwifty/CodableWrappers/blob/4eb46a4c656333e8514db8aad204445741de7d40/Sources/CodableWrappers/StaticCoders/DateCoding.swift#L60-L71
I was debugging an issue which was made a bit confusing because of throwing `valueNotFound`, would you like me to make a PR changing this to a `dataCorrupted` error?

It would match the behaviour of:
```swift
import Foundation

let string = """
{ "date": "ehrtrthrt" }
"""

struct Model: Codable {
  let date: Date
}

let decoder = JSONDecoder()
decoder.dateDecodingStrategy = .iso8601

do {
  let model = try decoder.decode(Model.self, from: Data(string.utf8))
} catch {
  if case DecodingError.dataCorrupted = error {
    print("DecodingError is dataCorrupted")
  } else {
    // not called
  }
}

```

**Comment by GottaGetSwifty** [comment]
Implemented here: https://github.com/GottaGetSwifty/CodableWrappers/releases/tag/3.0.0-alpha-release-2
