### ISSUE TITLE
Feature request: change name of key

### ISSUE THREAD

**Issue by jimbengtsson92** [GottaGetSwifty/CodableWrappers#34]
I would like to have a property wrapper that made it possible to change name of the key used when encoding and decoding. The result could look like this:
```
struct MyStruct: Codable {
   @CustomKey("key_in_json") var myOwnName: String
}
```

It is possible that I can do this by creating a [custom codable wrapper](https://github.com/GottaGetSwifty/CodableWrappers/blob/master/CustomExamples.md), but so far I have not been able to achieve it.
The [backed codable](https://github.com/jegnux/BackedCodable) package has support for this. I think it would be really nice if this package could include this as well :)

**Comment by GottaGetSwifty** [comment]
This is now possible (in beta) with Macros! here's the tag with the initial release: https://github.com/GottaGetSwifty/CodableWrappers/releases/tag/3.0.0-alpha-release-1

**Comment by GottaGetSwifty** [comment]
3.0 is now released! https://github.com/GottaGetSwifty/CodableWrappers/releases/tag/3.0.0

Thank you for your patience
