### ISSUE TITLE
Use default encoding with the optional wrapper

### ISSUE THREAD

**Issue by AlexisQapa** [GottaGetSwifty/CodableWrappers#6]
Hi,

What would be the simplest way to encode an optional as null if nil or use the default Codable encoding strategy if present ? I mean a generic way to do it on Codable to avoid writing static encoder for each of my Codable types.

so : 
struct some: Encodable {
  @??
  let thisShouldBeEncodedAsNull: String? = nil
  let thisShouldNotBeEncodedAsNull: String? = nil
}

would give in JSON: 
{
  "thisShouldBeEncodedAsNull": null
}

**Comment by GottaGetSwifty** [comment]
This should be possible, but may require some more complicated protocol/generic magic.

**Comment by GottaGetSwifty** [comment]
Added in https://github.com/GottaGetSwifty/CodableWrappers/releases/tag/2.0.0! See https://github.com/GottaGetSwifty/CodableWrappers#EncodeNulls
